# W1D4: Exploratory Data Analysis (EDA)

This notebook analyses a reproducible 20-student dataset. It runs `df.describe()`, `df.info()`, and `df.isnull().sum()`, imputes missing ML scores using the median, engineers average-score grades, and writes the required plots to `artifacts/eda`.

In [1]:
from pathlib import Path
import sys

repository_root = Path.cwd().resolve()
if not (repository_root / 'src').exists():
    repository_root = repository_root.parent
if str(repository_root) not in sys.path:
    sys.path.insert(0, str(repository_root))

from src.w1d4_eda import (
    create_student_dataset, engineer_features, inspect_data,
    plot_correlation_heatmap, plot_numeric_distributions,
    plot_top_categories, print_feature_summary,
)

In [2]:
raw_df = create_student_dataset()
inspect_data(raw_df)

print('=== Dataset Overview ===')
display(raw_df.head())
print(f'Shape: {raw_df.shape}')
print('\ndf.describe()')
display(raw_df.describe(include='all'))
print('\ndf.info()')
raw_df.info()
print('\ndf.isnull().sum()')
display(raw_df.isnull().sum())

=== Dataset Overview ===
   student_id       name  age  math  python  ml_score  attended
0           1  Student_1   23    70      62      89.0      True
1           2  Student_2   24    82      48      79.0      True
2           3  Student_3   22    61      69      43.0      True
3           4  Student_4   24    71      58       NaN      True
4           5  Student_5   24    93      94      45.0      True

Shape: (20, 7)

df.describe()
        student_id       name        age       math    python   ml_score  \
count     20.00000         20  20.000000  20.000000  20.00000  17.000000
unique         NaN         20        NaN        NaN       NaN        NaN
top            NaN  Student_1        NaN        NaN       NaN        NaN
freq           NaN          1        NaN        NaN       NaN        NaN
mean      10.50000        NaN  23.000000  76.050000  69.20000  71.058824
std        5.91608        NaN   1.337712  14.251408  16.52303  16.184370
min        1.00000        NaN  21.000000  52.000000  46.00000  43.000000
25%        5.75000        NaN  22.000000  64.750000  56.75000  57.000000
50%       10.50000        NaN  23.000000  75.000000  66.50000  73.000000
75%       15.25000        NaN  24.000000  88.750000  82.00000  83.000000
max       20.00000        NaN  25.000000  98.000000  97.00000  93.000000

       attended
count        20
unique        2
top        True
freq         16
mean        NaN
std         NaN
min         NaN
25%         NaN
50%         NaN
75%         NaN
max         NaN

df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  20 non-null     int64
 1   name        20 non-null     object
 2   age         20 non-null     int32
 3   math        20 non-null     int32
 4   python      20 non-null     int32
 5   ml_score    17 non-null     float64
 6   attended    20 non-null     bool
dtypes: bool(1), float64(1), int32(3), int64(1), object(1)
memory usage: 872.0+ bytes

df.isnull().sum()
student_id    0
name          0
age           0
math          0
python        0
ml_score      3
attended      0
dtype: int64
=== Dataset Overview ===

   student_id       name  age  math  python  ml_score  attended
0           1  Student_1   23    70      62      89.0      True
1           2  Student_2   24    82      48      79.0      True
2           3  Student_3   22    61      69      43.0      True
3           4  Student_4   24    71      58       NaN      True
4           5  Student_5   24    93      94      45.0      True

Shape: (20, 7)

df.describe()

,student_id,name,age,math,python,ml_score,attended
count,20.00000,20,20.000000,20.000000,20.00000,17.000000,20
unique,NaN,20,NaN,NaN,NaN,NaN,2
top,NaN,Student_1,NaN,NaN,NaN,NaN,True
freq,NaN,1,NaN,NaN,NaN,NaN,16
mean,10.50000,NaN,23.000000,76.050000,69.20000,71.058824,NaN
std,5.91608,NaN,1.337712,14.251408,16.52303,16.184370,NaN
min,1.00000,NaN,21.000000,52.000000,46.00000,43.000000,NaN
25%,5.75000,NaN,22.000000,64.750000,56.75000,57.000000,NaN
50%,10.50000,NaN,23.000000,75.000000,66.50000,73.000000,NaN
75%,15.25000,NaN,24.000000,88.750000,82.00000,83.000000,NaN
max,20.00000,NaN,25.000000,98.000000,97.00000,93.000000,NaN

df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  20 non-null     int64
 1   name        20 non-null     object
 2   age         20 non-null     int32
 3   math        20 non-null     int32
 4   python      20 non-null     int32
 5   ml_score    17 non-null     float64
 6   attended    20 non-null     bool
dtypes: bool(1), float64(1), int32(3), int64(1), object(1)
memory usage: 872.0+ bytes

df.isnull().sum()

student_id    0
name          0
age           0
math          0
python        0
ml_score      3
attended      0
dtype: int64

In [3]:
df = engineer_features(raw_df)

print('=== Grade Distribution ===')
display(df['grade'].value_counts().sort_index())
print('=== Top 5 Students ===')
display(df.nlargest(5, 'avg_score')[['name', 'avg_score', 'grade']])
print('=== Attendees vs Non-Attendees ===')
display(df.groupby('attended')['avg_score'].agg(['mean', 'count']).round(2))

=== Grade Distribution ===

grade
F     2
C    11
B     7
A     0
Name: count, dtype: int64

=== Top 5 Students ===

          name  avg_score grade
13  Student_14       84.7     B
15  Student_16       84.0     B
6    Student_7       83.0     B
7    Student_8       82.0     B
4    Student_5       77.3     B

=== Attendees vs Non-Attendees ===

           mean  count
attended
False     76.75      4
True      71.08     16

In [4]:
plot_numeric_distributions(df)
plot_correlation_heatmap(df)
plot_top_categories(df)

print('Saved: artifacts/eda/numeric_distributions.png')
print('Saved: artifacts/eda/correlation_heatmap.png')
print('Saved: artifacts/eda/top_10_category_counts.png')

Saved: artifacts/eda/numeric_distributions.png
Saved: artifacts/eda/correlation_heatmap.png
Saved: artifacts/eda/top_10_category_counts.png

## Five observations

1. There are 20 students and three missing values, all in `ml_score`.
2. Ages range only from 21 to 25.
3. Median imputation keeps all 20 records for the score analysis.
4. Grades are concentrated in C (11 students) and B (7 students); no student receives A.
5. Attendance groups are imbalanced (16 attendees and 4 non-attendees), so their average-score difference is not a reliable causal finding.

The complete 200-word narrative is in `docs/w1d4_eda_narrative.md`.